apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 19.1.7
    chart: elasticsearch
    helm:
      values: |
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "1000m"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true