apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://helm.elastic.co'
    targetRevision: 7.17.3
    chart: elasticsearch
    helm:
      values: |
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true