apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://fluent.github.io/helm-charts'
    targetRevision: 0.20.5
    chart: fluent-bit
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true