apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 10.1.19
    chart: kibana
    helm:
      values: |
        service:
          type: LoadBalancer
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "1000m"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true